# Generated by Django 2.1 on 2019-06-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
